name: bluetooth_chat
description: A Bluetooth messaging app
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bluetooth_serial: ^0.4.0
  provider: ^6.0.5
  intl: ^0.18.1
  sqflite: ^2.3.0
  path: ^1.8.3
  image_picker: ^1.0.4
  file_picker: ^5.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2 